const GPX_URL='calm_lil_wednesday_excursion.gpx';
const sections=[...document.querySelectorAll('.story-section')], routePaths=[...document.querySelectorAll('[data-route-path]')], dots=[...document.querySelectorAll('[data-route-dot]')], cards=[...document.querySelectorAll('.media-card')];
let routeLength=1, activeProgress=0, activeMedia=0, dragging=false, scrollLock=false, editing=false, moveState=null;

// The editable source of truth. `at` controls when media appears; x/y/w/h are percentages inside the right-hand region.
const defaultMediaPlan=[
 {id:'img-01',at:.04,order:0,x:4,y:5,w:52,h:23},{id:'img-02',at:.16,order:1,x:62,y:6,w:34,h:19},{id:'img-03',at:.30,order:2,x:3,y:31,w:44,h:22},
 {id:'img-04',at:.45,order:3,x:51,y:30,w:45,h:24},{id:'img-05',at:.60,order:4,x:6,y:58,w:34,h:18},{id:'video-01',at:.75,order:5,x:44,y:59,w:52,h:20},{id:'img-07',at:.91,order:6,x:19,y:82,w:45,h:15}
];
let mediaPlan=defaultMediaPlan.map(item=>({...item}));
function parseGPX(xml){const doc=new DOMParser().parseFromString(xml,'application/xml');return[...doc.querySelectorAll('trkpt')].map(n=>({lat:+n.getAttribute('lat'),lon:+n.getAttribute('lon')})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));}
function thin(points,max=700){if(points.length<=max)return points;const stride=(points.length-1)/(max-1);return Array.from({length:max},(_,i)=>points[Math.round(i*stride)]);}
function makeRawRoutePath(points){const mean=points.reduce((s,p)=>s+p.lat,0)/points.length,cos=Math.cos(mean*Math.PI/180),projected=points.map(p=>({x:p.lon*cos,y:-p.lat})),xs=projected.map(p=>p.x),ys=projected.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),xr=maxX-minX||1,yr=maxY-minY||1,scale=Math.min(86/xr,92/yr),left=(100-xr*scale)/2,top=(100-yr*scale)/2;return projected.map((p,i)=>`${i?'L':'M'}${(left+(p.x-minX)*scale).toFixed(3)},${(top+(p.y-minY)*scale).toFixed(3)}`).join(' ');}
function itemFor(id){return mediaPlan.find(item=>item.id===id);}
function renderMedia(){const sorted=[...mediaPlan].sort((a,b)=>a.order-b.order);cards.forEach(card=>{const item=itemFor(card.dataset.mediaId),index=sorted.findIndex(x=>x.id===item.id),distance=index-activeMedia;card.style.left=`${item.x}%`;card.style.top=`${item.y}%`;card.style.width=`${item.w}%`;card.style.height=`${item.h}%`;card.style.transform=`translateX(${distance*12}px)`;card.classList.toggle('active',index===activeMedia);});}
function setProgress(progress,shouldScroll=false){activeProgress=Math.max(0,Math.min(1,progress));dots.forEach(dot=>{const p=dot.closest('svg').querySelector('.route-line').getPointAtLength(routeLength*activeProgress);dot.setAttribute('cx',p.x);dot.setAttribute('cy',p.y);dot.setAttribute('aria-valuenow',String(Math.round(activeProgress*100)));});const passed=mediaPlan.map((item,index)=>({item,index})).filter(x=>x.item.at<=activeProgress);activeMedia=passed.length?mediaPlan.slice().sort((a,b)=>a.at-b.at).findIndex(x=>x.id===passed[passed.length-1].item.id):0;renderMedia();cards.forEach(card=>{const video=card.querySelector('video');if(video){if(card.classList.contains('active'))video.play().catch(()=>{});else video.pause();}});if(shouldScroll&&!scrollLock){scrollLock=true;scrollTo({top:(document.documentElement.scrollHeight-innerHeight)*activeProgress,behavior:'auto'});requestAnimationFrame(()=>scrollLock=false);}}
function closestProgress(event,svg){const rect=svg.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width*100,y=(event.clientY-rect.top)/rect.height*100,path=svg.querySelector('.route-line');let best={d:Infinity,p:activeProgress};for(let i=0;i<=360;i++){const p=i/360,point=path.getPointAtLength(routeLength*p),d=(point.x-x)**2+(point.y-y)**2;if(d<best.d)best={d,p};}return best.p;}
function moveDot(event,dot){setProgress(closestProgress(event,dot.closest('svg')),true);}
dots.forEach(dot=>{dot.addEventListener('pointerdown',e=>{dragging=true;dot.setPointerCapture(e.pointerId);moveDot(e,dot);});dot.addEventListener('pointermove',e=>{if(dragging)moveDot(e,dot);});dot.addEventListener('pointerup',()=>dragging=false);dot.addEventListener('keydown',e=>{if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const d=e.key==='ArrowUp'||e.key==='ArrowLeft'?-0.02:e.key==='Home'?-1:e.key==='End'?1:0.02;setProgress(e.key==='Home'?0:e.key==='End'?1:activeProgress+d,true);});});
const observer=new IntersectionObserver(entries=>{if(scrollLock||dragging)return;const active=entries.filter(e=>e.isIntersecting).sort((a,b)=>Math.abs(a.boundingClientRect.top)-Math.abs(b.boundingClientRect.top))[0];if(active)setProgress(+active.target.dataset.section/(sections.length-1));},{threshold:.1,rootMargin:'-35% 0px -48% 0px'});sections.forEach(section=>observer.observe(section));

function editableElements(){return[...document.querySelectorAll('.editable,h1[contenteditable]')];}
function savePage(){localStorage.setItem('sf-ride-page',JSON.stringify({texts:editableElements().map(el=>el.innerHTML),media:mediaPlan}));}
function loadPage(){try{const saved=JSON.parse(localStorage.getItem('sf-ride-page'));if(!saved)return;editableElements().forEach((el,i)=>{if(saved.texts?.[i]!==undefined)el.innerHTML=saved.texts[i];});if(saved.media?.every(item=>item.id&&Number.isFinite(item.at)&&Number.isFinite(item.x)&&Number.isFinite(item.y)&&Number.isFinite(item.w)&&Number.isFinite(item.h)))mediaPlan=saved.media;}catch{/* ignore invalid local drafts */}}
function renderControls(){const box=document.querySelector('#mediaControls');box.innerHTML='<div class="controls-title">media manifest</div>'+[...mediaPlan].sort((a,b)=>a.order-b.order).map(item=>`<div class="control-row" data-id="${item.id}"><b>${item.id}</b><label>route <input data-key="at" type="range" min="0" max="100" value="${Math.round(item.at*100)}"></label><label>order <input data-key="order" type="number" min="0" max="99" value="${item.order}"></label><label>x <input data-key="x" type="number" min="0" max="100" value="${item.x}"></label><label>y <input data-key="y" type="number" min="0" max="100" value="${item.y}"></label><label>w <input data-key="w" type="number" min="5" max="100" value="${item.w}"></label><label>h <input data-key="h" type="number" min="5" max="100" value="${item.h}"></label></div>`).join('');box.querySelectorAll('.control-row input').forEach(input=>input.addEventListener('input',()=>{const item=itemFor(input.closest('.control-row').dataset.id),key=input.dataset.key;item[key]=key==='at'?+input.value/100:+input.value;renderMedia();}));}
function setEditing(value){editing=value;document.body.classList.toggle('editing',editing);editableElements().forEach(el=>el.contentEditable=String(editing));document.querySelector('#editButton').hidden=editing;document.querySelector('#saveButton').hidden=!editing;document.querySelector('#copyButton').hidden=!editing;document.querySelector('#resetButton').hidden=!editing;document.querySelector('#mediaControls').hidden=!editing;if(editing){renderControls();editableElements()[0]?.focus();}}
document.querySelector('#editButton').addEventListener('click',()=>setEditing(true));document.querySelector('#saveButton').addEventListener('click',()=>{savePage();setEditing(false);});document.querySelector('#resetButton').addEventListener('click',()=>{localStorage.removeItem('sf-ride-page');location.reload();});document.querySelector('#copyButton').addEventListener('click',async()=>{const manifest=JSON.stringify(mediaPlan,null,2);try{await navigator.clipboard.writeText(manifest);document.querySelector('#copyButton').textContent='copied';setTimeout(()=>document.querySelector('#copyButton').textContent='{ }',1200);}catch{prompt('copy this media manifest',manifest);}});
cards.forEach(card=>{const handle=document.createElement('i');handle.className='resize-handle';card.append(handle);card.addEventListener('pointerdown',event=>{if(!editing)return;const item=itemFor(card.dataset.mediaId),parent=document.querySelector('#mediaRegion').getBoundingClientRect(),rect=card.getBoundingClientRect(),resize=event.target.classList.contains('resize-handle');moveState={card,item,parent,startX:event.clientX,startY:event.clientY,start:{x:item.x,y:item.y,w:item.w,h:item.h},resize};card.setPointerCapture(event.pointerId);});card.addEventListener('pointermove',event=>{if(!moveState||moveState.card!==card)return;const dx=(event.clientX-moveState.startX)/moveState.parent.width*100,dy=(event.clientY-moveState.startY)/moveState.parent.height*100;if(moveState.resize){moveState.item.w=Math.max(5,moveState.start.w+dx);moveState.item.h=Math.max(5,moveState.start.h+dy);}else{moveState.item.x=Math.max(0,Math.min(100-moveState.item.w,moveState.start.x+dx));moveState.item.y=Math.max(0,Math.min(100-moveState.item.h,moveState.start.y+dy));}renderMedia();});card.addEventListener('pointerup',()=>{if(moveState?.card===card){moveState=null;renderControls();}});});
loadPage();setEditing(false);
fetch(GPX_URL).then(r=>r.ok?r.text():Promise.reject()).then(xml=>{const d=makeRawRoutePath(thin(parseGPX(xml)));routePaths.forEach(path=>path.setAttribute('d',d));routeLength=document.querySelector('.route-map .route-line').getTotalLength();const points=parseGPX(xml),center=points[Math.floor(points.length/2)];document.querySelector('#mapView').innerHTML=`<iframe title="Interactive Google Maps route area" src="https://www.google.com/maps?q=${center.lat},${center.lon}&z=11&output=embed" loading="lazy"></iframe>`;setProgress(0);}).catch(()=>setProgress(0));
